### PR TITLE
extension

### PR DESCRIPTION
**Pull request by poundde**
extension system pls merge

### CODE REVIEW

**Comment by radmanplays** [comment]
can you add scrolling through categories?

**Comment by radmanplays** [comment]
and also i get this error when i try to load any extensions:
VM78:116 Uncaught (in promise) ReferenceError: EaglerBuilder is not defined
    at eval (eval at click_handler_4 (+page.svelte:751:17), <anonymous>:116:1)
    at HTMLDivElement.click_handler_4 (+page.svelte:751:17)

**Comment by OeildeLynx31** [comment]
> can you add scrolling through categories?

He tested, but the extension system he did is not compatible with the continuous toolbox plugin, so for now it is impossible. But maybe in the future we will add this feature again.

**Comment by poundde** [comment]
> and also i get this error when i try to load any extensions: VM78:116 Uncaught (in promise) ReferenceError: EaglerBuilder is not defined at eval (eval at click_handler_4 (+page.svelte:751:17), :116:1) at HTMLDivElement.click_handler_4 (+page.svelte:751:17)

it works fine on my workspace maybe lynx should change the command to npm run dev

**Comment by OeildeLynx31** [comment]
We are still working on it, but now directly on the branch.

**Pull request merged**
